import Head from 'next/head';
import  connectarDB  from '../lib/mongoose';
import Movies from '../models/Movies';
import Link from 'next/link';


export default function Home({movies}) {

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main >
        <h1 style={{display: 'flex', justifyContent: 'center', marginBottom: 30}}>Movies</h1>
        <div style={{display: 'flex', justifyContent: 'center', marginBottom: 20}}>
        <Link legacyBehavior href={'/new'}>
          <a className="btn btn-primary w-50">Add Movie</a>
        </Link>
        </div>
        {
          movies.map(({_id, title, plot}) => 
             <div key={_id} className="card card-body border border-info rounded" style={{borderWidth: 32, display: 'flex', flexDirection: 'column', margin: 10, textAlign: 'center'}}>
              <Link legacyBehavior href={`/${_id}`}>
                <div>
                    <h4>title: {title} </h4>
                       <h4>plot: {plot}</h4>
                    <br></br>
                </div>
              </Link>
             </div>
          )
        }
      </main>
    </>
  )
}

export async function getServerSideProps() {
  try {
      await connectarDB();
      const res = await Movies.find({});

      const movies = res.map(doc => {
        const movie = doc.toObject();
        movie._id = `${movie._id}`;
        return movie;
      })

      return {props: {movies}};
  } catch (error) {
     console.log(error)
  }
  
}
